import React, { createContext, useContext, useState } from "react";

// Dữ liệu từ điển ngôn ngữ cho toàn bộ ứng dụng người dùng
export const translations = {
    vi: {
        // Navigation / Header
        nav_movies: "Phim",
        nav_cinemas: "Rạp chiếu",
        nav_news: "Ưu đãi",
        search_placeholder: "Tìm phim, rạp...",
        login: "Đăng nhập",
        register: "Đăng ký",
        profile: "Thông tin cá nhân",
        booked_tickets: "Lịch sử đặt vé",
        change_password: "Đổi mật khẩu",
        logout: "Đăng xuất",
        theme_light: "Giao diện sáng",
        theme_dark: "Giao diện tối",
        notifications: "Thông báo",
        no_notifications: "Không có thông báo mới",

        // Home / Hero
        explore_now: "Khám Phá Ngay",
        infinite_journey: "Hành Trình Vô Tận",
        hero_desc: "Một kiệt tác điện ảnh khoa học viễn tưởng đưa bạn đến những ngôi sao xa xôi nhất. Khám phá những bí ẩn của vũ trụ trong một hành trình đầy cảm xúc và hình ảnh tuyệt đẹp.",
        more_info: "Thêm Thông Tin",

        // Home / Promotions
        special_promotions: "Khuyến Mãi Đặc Biệt",
        claim_code: "Nhận Mã",
        claimed: "Đã Nhận ✓",
        promo_family_title: "Chủ Nhật Gia Đình",
        promo_family_desc: "Giảm 20% gói combo gia đình khi xem phim vào các ngày Chủ Nhật.",
        promo_vip_title: "Giảm 20% Thành Viên",
        promo_vip_desc: "Ưu đãi đặc biệt: Giảm 20% giá vé cho thành viên VIP của mievoh.",
        promo_student_title: "Ưu Đãi Học Sinh Sinh Viên",
        promo_student_desc: "Đồng giá vé 45K cho học sinh sinh viên vào các ngày trong tuần từ Thứ Hai đến Thứ Năm.",
        promo_night_title: "Vé Xem Phim Đêm muộn",
        promo_night_desc: "Đồng giá 50K cho các suất chiếu sau 22:00 hàng ngày dành cho các cú đêm.",
        promo_couple_title: "Combo Cặp Đôi Ngọt Ngào",
        promo_couple_desc: "Tiết kiệm 10% khi mua Combo Cặp Đôi (2 nước + 1 bắp lớn) tại quầy bắp nước.",

        // Home / News
        movie_news: "Tin Tức Điện Ảnh",
        see_all: "Xem Tất Cả",
        news_art1_title: "Top 5 phim phải xem trong tháng này",
        news_art1_desc: "Tổng hợp những bom tấn điện ảnh đang khuấy đảo phòng vé mà bạn không thể bỏ lỡ.",
        news_art2_title: "Phỏng vấn độc quyền với đạo diễn 'Hành Trình Vô Tận'",
        news_art2_desc: "Khám phá quá trình sáng tạo đằng sau kiệt tác khoa học viễn tưởng đang làm mưa làm gió hiện nay.",
        news_art3_title: "Tiết lộ bí mật hậu trường chưa từng công bố",
        news_art3_desc: "Cùng điểm qua những điều thú vị diễn ra phía sau ống kính của các dự án điện ảnh lớn.",
        news_cat_news: "Tin tức",
        news_cat_interview: "Phỏng vấn",
        news_cat_bts: "Hậu trường",

        // Login / Register
        sign_up_title: "Đăng Ký",
        sign_up_subtitle: "Tham gia cộng đồng điện ảnh Mievoh",
        username: "Tên đăng nhập",
        full_name: "Họ và tên",
        email_address: "Địa chỉ Email",
        phone_number: "Số điện thoại",
        password: "Mật khẩu",
        confirm_password: "Xác nhận mật khẩu",
        signing_up: "Đang đăng ký...",
        sign_in_title: "Đăng Nhập",
        sign_in_subtitle: "Chào mừng bạn quay trở lại với Mievoh Cinema",
        forgot_password: "Quên mật khẩu?",
        forgot_password_title: "Quên Mật Khẩu",
        forgot_password_subtitle: "Nhập địa chỉ email của bạn để khôi phục tài khoản",
        verify_email: "Xác minh Email",
        verifying: "Đang xác minh...",
        back_to_sign_in: "Quay lại Đăng nhập",
        reset_password_title: "Đặt Lại Mật Khẩu",
        reset_password_subtitle: "Nhập mật khẩu an toàn mới của bạn",
        new_password: "Mật khẩu mới",
        confirm_new_password: "Xác nhận mật khẩu mới",
        reset_password_btn: "Đặt lại mật khẩu",
        resetting: "Đang đặt lại...",
        signing_in: "Đang đăng nhập...",
        or_divider: "hoặc",
        sign_in_google: "Đăng nhập với Google",
        toast_otp_sent: "Mã OTP đã được gửi đến email của bạn.",
        otp_invalid_length: "Mã OTP phải có 6 chữ số.",
        otp_modal_title: "Xác Thực OTP",
        otp_modal_subtitle: "Chúng tôi đã gửi mã xác thực gồm 6 chữ số đến email",
        otp_input_placeholder: "Nhập mã OTP",
        otp_verify_btn: "Xác thực OTP",
        otp_verifying: "Đang xác thực...",
        otp_resend_btn: "Gửi lại OTP",
        otp_resending: "Đang gửi...",
        otp_cancel_btn: "Hủy",
        welcome_back_overlay: "Chào Mừng Trở Lại!",
        welcome_back_desc: "Để tiếp tục kết nối với chúng tôi, vui lòng đăng nhập",
        hello_friend_overlay: "Chào Bạn Mới!",
        hello_friend_desc: "Nhập thông tin cá nhân của bạn để bắt đầu hành trình",
        sign_up_now: "ĐĂNG KÝ NGAY",
        already_have_account: "Đã có tài khoản?",
        already_have_account_desc: "Đăng nhập ngay để tiếp tục đặt vé xem các bộ phim bom tấn và nhận ưu đãi độc quyền từ Mievoh!",
        sign_in_btn: "ĐĂNG NHẬP",
        cancel_btn: "Hủy",

        // Validation & Messages
        email_registered: "Email này đã được đăng ký",
        validation_required: "Trường này là bắt buộc",
        loading: "Đang tải...",
        no_showtimes: "Không có suất chiếu nào cho ngày này.",

        // Select Seat
        screen: "Màn hình",
        seat_status_available: "Trống",
        seat_status_selected: "Đang chọn",
        seat_status_booked: "Đã bán",
        seat_status_holding: "Đang giữ",
        seat_type_regular: "Ghế Thường",
        seat_type_vip: "Ghế VIP",
        seat_type_sweetbox: "Ghế Đôi Sweetbox",
        booking_summary: "Thông tin thanh toán",
        booking_movie: "Phim",
        booking_cinema: "Rạp",
        booking_showtime: "Suất chiếu",
        booking_seats: "Ghế chọn",
        booking_combo: "Combo đã chọn",
        booking_total: "Tổng cộng",
        booking_continue: "Tiếp tục",
        select_seat_title: "Chọn Ghế",

        // Book Ticket / Booking Sidebar / Ticket Page
        select_showtime: "Chọn Suất Chiếu",
        select_date: "Chọn Ngày",
        choose_combo: "Chọn Combo Bắp Nước",
        combo_desc: "Thêm combo bắp nước để trải nghiệm xem phim tuyệt vời hơn",
        next_step: "Bước tiếp theo",
        prev_step: "Quay lại",
        payment_method: "Phương thức thanh toán",
        confirm_payment: "Xác nhận thanh toán",
        // Additional Select Seat / Book Ticket / Profile / HotMovies / Cinemas
        stepper_combos: "Combo",
        stepper_payment: "Thanh toán",
        stepper_ticket_info: "Thông tin vé",
        booking_hall: "Phòng chiếu",
        booking_format: "Định dạng",
        no_seats_selected: "Chưa chọn ghế",
        ticket_price: "Giá vé",
        creating_transaction: "Đang tạo giao dịch...",
        pay_now: "Thanh toán ngay",
        booking_terms_reminder: "Vé đã mua không thể thay đổi, hoàn tiền hoặc hủy. Vui lòng kiểm tra kỹ suất chiếu và ghế đã chọn trước khi xác nhận.",
        toast_account_number_copied: "Đã sao chép số tài khoản!",
        toast_transfer_content_copied: "Đã sao chép nội dung chuyển khoản!",
        toast_payment_success: "Thanh toán thành công! Vé của bạn đã được xuất.",
        toast_screenshot_captured: "Đã chụp màn hình! Vui lòng mở ứng dụng ngân hàng để quét QR.",
        toast_register_success: "Đăng ký tài khoản thành công!",
        toast_payment_initiated: "Đã khởi tạo giao dịch thanh toán!",
        toast_login_success: "Đăng nhập thành công!",
        toast_login_failed: "Đăng nhập thất bại!",
        toast_google_login_success: "Đăng nhập Google thành công!",
        toast_email_verified_success: "Xác minh email thành công!",
        toast_password_reset_success: "Đặt lại mật khẩu thành công!",
        toast_seat_hold_expired: "Thời gian giữ ghế đã hết hạn. Vui lòng chọn lại ghế!",
        toast_max_seats_limit: "Bạn chỉ có thể chọn tối đa 8 ghế",
        toast_select_seat_required: "Vui lòng chọn ít nhất một ghế trước khi thanh toán",
        toast_fix_info_errors: "Vui lòng sửa các lỗi thông tin cá nhân",
        toast_username_required: "Vui lòng nhập tên tài khoản!",
        toast_email_required: "Vui lòng nhập địa chỉ email!",
        toast_password_required: "Vui lòng nhập mật khẩu!",
        cinema_locations_label: "Khu Vực Chiếu",

        format_2d_subbed: "2D Phụ Đề",
        format_2d_dubbed: "2D Lồng Tiếng",
        cinema_chains_label: "Hệ Thống Rạp",
        cinema_network_title: "Mạng Lưới Rạp Toàn Quốc",
        cinema_network_desc: "Tìm chi nhánh rạp chiếu phim gần bạn nhất. Xem địa chỉ chi tiết, thông tin liên hệ, giá vé và lịch chiếu của tất cả các hệ thống rạp hàng đầu tại Việt Nam.",
        filter_select_location: "Chọn Vị Trí:",
        filter_cinema_chain: "Hệ Thống Rạp:",
        filter_quick_search: "Tìm Kiếm Nhanh:",
        filter_all_chains: "Tất Cả Hệ Thống ({count})",
        filter_all_chains_with_count: "Tất Cả Hệ Thống ({count} rạp)",
        filter_search_placeholder: "Nhập tên rạp, tên đường...",
        no_cinemas_found: "Không tìm thấy rạp phim",
        no_cinemas_found_desc: "Rất tiếc, không tìm thấy rạp phim nào phù hợp với bộ lọc hiện tại. Vui lòng thử lại với tùy chọn khác.",
        clear_filters: "Xóa Bộ Lọc",
        order_confirmation: "Xác nhận đơn hàng",
        personal_info: "Thông tin cá nhân",
        total_order_value: "Tổng giá trị đơn hàng",
        proceed_to_pay: "Tiến hành thanh toán",
        qr_transfer: "Chuyển khoản QR ngân hàng",
        momo_wallet: "Ví điện tử MoMo",
        zalopay_wallet: "Ví điện tử ZaloPay",
        atm_card: "Thẻ ATM nội địa",
        qr_transfer_name: "Chuyển khoản QR ngân hàng",
        qr_transfer_desc: "Quét mã QR bằng ứng dụng ngân hàng để thanh toán",
        momo_name: "Ví MoMo",
        momo_desc: "Thanh toán nhanh bằng ví điện tử MoMo",
        zalopay_name: "Ví ZaloPay",
        zalopay_desc: "Thanh toán bằng ZaloPay với nhiều ưu đãi hấp dẫn",
        atm_name: "Thẻ ATM nội địa",
        atm_desc: "Thanh toán bằng thẻ ngân hàng nội địa",
        back_to_combos: "Quay lại chọn combo",
        full_name_placeholder: "Nhập họ và tên của bạn",
        phone_number_placeholder: "Nhập số điện thoại của bạn",
        email_address_placeholder: "Nhập địa chỉ email của bạn",
        popcorn_drinks_combos: "Bắp nước & Combo",
        popcorn_combo_discount_desc: "Tiết kiệm đến 20% khi mua cùng vé",
        back_to_seats: "Quay lại chọn ghế",
        verifying_bank_transfer: "Đang xác minh giao dịch chuyển khoản...",
        please_wait_moment: "Vui lòng chờ trong giây lát",
        transfer_money_to_account: "Chuyển khoản tới tài khoản sau",
        transfer_time_limit_desc: "Bạn cần chuyển khoản trong vòng {time} nếu không ghế của bạn sẽ được giải phóng.",
        bank_label: "Ngân hàng",
        account_number_label: "Số tài khoản",
        account_holder_label: "Chủ tài khoản",
        transfer_content_label: "Nội dung chuyển khoản",
        copy_btn: "Sao chép",
        amount_label: "Số tiền",
        enter_exact_content_desc: "Nhập chính xác nội dung để nhận được mã vé.",
        hotline_reminder_desc: "Hệ thống tự động xuất mã vé trong vòng 30s sau khi chuyển khoản thành công. Vui lòng liên hệ hotline 024 7308 8890 nếu bạn không nhận được mã vé.",
        cancel_transaction: "Hủy giao dịch",
        confirm_successful_transfer: "Tôi đã chuyển khoản thành công",
        screenshot_qr_desc: "Chụp màn hình để quét mã QR",
        booking_success_title: "Đặt vé thành công!",
        booking_success_desc: "Cảm ơn bạn đã lựa chọn Mievoh. Suất chiếu của bạn đang chờ đợi.",
        booking_hall_seats: "Phòng chiếu & Ghế",
        attached_combos: "Combo kèm theo",
        total_amount_paid: "Tổng số tiền đã thanh toán:",
        scan_barcode_desc: "Quét mã vạch tại rạp để in vé vào cổng",
        back_to_homepage: "Quay lại Trang chủ",
        movie_details: "Chi tiết phim",
        cinema_locations: "Khu vực",
        no_cinemas_available: "Không có rạp khả dụng",
        no_cinemas_available_desc: "Vui lòng thay đổi bộ lọc khu vực hoặc chọn ngày chiếu khác.",
        trending_movies: "Phim Hot Đang Chiếu",
        recommended_movies: "Phim được đề xuất với bạn",
        quick_book: "Đặt vé nhanh",
        featured_cinemas: "Hệ thống rạp",
        see_all_cinemas: "Xem tất cả",
        view_showtimes: "Xem lịch chiếu",
        access_denied: "Quyền truy cập bị từ chối",
        profile_access_denied_desc: "Vui lòng đăng nhập để xem thông tin cá nhân và lịch sử giao dịch của bạn.",
        session_expired: "Phiên làm việc đã hết hạn. Vui lòng đăng nhập lại.",
        login_now_btn: "Đăng nhập ngay",
        click_star_avatar: "Nhấp vào ngôi sao để chọn và cập nhật ảnh đại diện",
        avatar_url_label: "Ảnh đại diện (URL)",
        change_password_title: "Đổi mật khẩu",
        ticket_history_title: "Lịch sử đặt vé",
        avatar_updated_success: "Cập nhật ảnh đại diện thành công!",
        profile_updated_success: "Cập nhật hồ sơ thành công!",
        failed_to_update_profile: "Cập nhật hồ sơ thất bại",
        no_name_registered: "Chưa đăng ký họ tên",
        no_email_registered: "Chưa đăng ký email",
        no_phone_number_registered: "Chưa đăng ký số điện thoại",
        gender: "Giới tính",
        gender_not_selected: "Chưa chọn giới tính",
        gender_male: "Nam",
        gender_female: "Nữ",
        select_gender: "Chọn giới tính",
        age: "Tuổi",
        age_not_provided: "Chưa cung cấp tuổi",
        age_auto_calculated: "Tuổi (Tự động tính)",
        calculated_from_dob: "Tính từ ngày sinh",
        date_of_birth: "Ngày sinh",
        dob_not_set: "Chưa đặt ngày sinh",
        dob_day: "Ngày",
        dob_month: "Tháng",
        dob_year: "Năm",
        address: "Địa chỉ",
        address_not_set: "Chưa đặt địa chỉ",
        cccd: "CCCD/CMND",
        cccd_not_linked: "Chưa liên kết CCCD",
        edit_profile_btn: "Chỉnh sửa cá nhân",
        saving_btn: "Đang lưu...",
        saved_btn: "Đã lưu!",
        save_changes_btn: "Lưu thay đổi",
        current_password: "Mật khẩu hiện tại",
        current_password_required: "Mật khẩu hiện tại là bắt buộc",
        current_password_placeholder: "Nhập mật khẩu hiện tại",
        new_password_placeholder: "Nhập mật khẩu mới",
        confirm_new_password_placeholder: "Xác nhận lại mật khẩu mới",
        password_changed_success: "Đổi mật khẩu thành công!",
        password_changed_failed: "Đổi mật khẩu thất bại",
        updating_btn: "Đang cập nhật...",
        updated_success_btn: "Cập nhật thành công!",
        update_password_btn: "Cập nhật mật khẩu",
        no_tickets_booked: "Chưa có vé nào được đặt.",
        paid_status: "Đã thanh toán",
        booked_on: "Đặt ngày",
        view_ticket_code: "Xem mã vé",
        click_to_scan: "Nhấp để quét",
        ticket_receipt_code: "Mã nhận vé",
        scan_at_counter_desc: "Quét tại quầy soát vé để vào rạp",
        // Movie System
        genre_action: "Hành động",
        genre_scifi: "Viễn tưởng",
        genre_romance: "Lãng mạn",
        genre_music: "Âm nhạc",
        genre_mystery: "Bí ẩn",
        genre_thriller: "Giật gân",
        genre_comedy: "Hài hước",
        genre_family: "Gia đình",
        genre_adventure: "Phiêu lưu",
        genre_animation: "Hoạt hình",
        genre_crime: "Hình sự",
        genre_horror: "Kinh dị",
        genre_sports: "Thể thao",
        genre_drama: "Kịch tính",
        genre_documentary: "Tài liệu",
        genre_nature: "Thiên nhiên",

        coming_soon: "Sắp Chiếu",
        now_showing: "Đang Chiếu",
        buy_ticket: "Mua Vé",
        get_notified: "Nhận Thông Báo",
        subscribed_notifications: "Đã đăng ký nhận thông báo cho \"{title}\" khi phim khởi chiếu!",
        opening_booking_for: "Đang mở trang đặt vé cho phim: {title}",

        release_date: "Khởi Chiếu",
        director: "Đạo Diễn",
        cast: "Diễn Viên",
        age_rating: "Độ Tuổi",
        duration: "Thời Lượng",
        language_label: "Ngôn Ngữ",
        based_on_reviews: "(5.0 / 5 dựa trên đánh giá)",
        reviews_audience: "Đánh Giá Từ Khán Giả ({count})",
        reviews_star_count: "{count} sao",
        reviews_based_on: "Dựa trên {count} đánh giá",
        reviews_no_reviews: "Chưa có đánh giá nào. Hãy là người đầu tiên đánh giá!",
        reviews_write_review: "Viết Đánh Giá Của Bạn",
        reviews_your_rating: "Đánh giá của bạn:",
        reviews_your_name: "Họ và tên *",
        reviews_name_placeholder: "Nhập tên của bạn để hiển thị trên đánh giá...",
        reviews_comment_label: "Nội dung bình luận:",
        reviews_comment_placeholder: "Chia sẻ suy nghĩ của bạn về bộ phim này...",
        reviews_submit: "Gửi Đánh Giá",
        reviews_enter_name_toast: "Vui lòng nhập tên của bạn!",
        reviews_enter_comment_toast: "Vui lòng viết bình luận!",
        reviews_success_toast: "Cảm ơn bạn đã gửi đánh giá!",
        watch_trailer: "Xem Trailer",
        movie_not_found: "Không Tìm Thấy Phim",
        movie_not_found_desc: "Rất tiếc, bộ phim yêu cầu không tồn tại hoặc đã ngừng chiếu.",
        back_to_movie_list: "Quay Lại Danh Sách",

        movie_list_title: "Danh Sách Phim",
        movie_list_subtitle: "Khám phá thế giới điện ảnh đỉnh cao với những bộ phim bom tấn hot nhất đang chiếu và sắp chiếu tại Mievoh.",

        all_filter: "Tất Cả",
        all_locations: "Tất Cả Khu Vực",
        now_showing_filter: "Đang Chiếu",
        coming_soon_filter: "Sắp Chiếu",
        search_movies_placeholder: "Tìm phim...",
        sort_by_label: "Sắp xếp:",
        highest_rating: "Đánh giá cao nhất",
        title_az: "Tên phim (A - Z)",
        title_za: "Tên phim (Z - A)",
        genre_label: "Thể loại:",

        twod_dubbed: "2D Lồng Tiếng",
        twod_subbed: "2D Phụ Đề",
        footer_desc: "Trải nghiệm điện ảnh đỉnh cao. Đặt vé dễ dàng, thưởng thức trọn vẹn.",
        footer_rights: "© 2024 mievoh. Toàn bộ quyền được bảo lưu.",
        footer_explore: "Khám Phá",
        footer_about: "Về Chúng Tôi",
        footer_terms: "Điều Khoản Dịch Vụ",
        footer_privacy: "Chính Sách Quyền Riêng Tư",
        footer_support: "Hỗ Trợ",
        footer_help: "Trung Tâm Trợ Giúp",
        footer_contact: "Liên Hệ",
        footer_faq: "Câu Hỏi Thường Gặp",
        footer_download: "Tải Ứng Dụng",
        booking_saved_history_success: "Đã lưu thành công mã vé {code} vào lịch sử của bạn!",

        // Admin
        admin_dashboard: "Dashboard",
        admin_movies: "Quản lý Phim",
        admin_cinema_systems: "Hệ thống rạp",
        admin_cinema_complexes: "Cụm rạp",
        admin_cinemas: "Phòng chiếu",
        admin_showtimes: "Lịch chiếu",
        admin_foods: "Đồ ăn & Combo",
        admin_banners: "Banner",
        admin_staff: "Quản lý nhân viên",
        admin_users: "Quản lý người dùng",
        admin_vouchers: "Mã giảm giá",
        admin_notifications: "Thông báo",
        admin_recommendations: "Recommend & Email",
        admin_statistics: "Thống kê",
        admin_title: "Mievoh Staff",
        admin_access_denied: "Truy cập bị từ chối",
        admin_no_permission: "Bạn không có quyền truy cập trang quản trị.",
        admin_switch_member: "Member",
        admin_switch_admin: "Admin",

        // Admin - Common actions / labels
        adm_loading: "Đang tải...",
        adm_loading_data: "Đang tải dữ liệu...",
        adm_saving: "Đang lưu...",
        adm_save: "Lưu",
        adm_add: "Thêm mới",
        adm_update: "Cập nhật",
        adm_cancel: "Hủy",
        adm_delete: "Xóa",
        adm_edit: "Sửa",
        adm_close: "Đóng",
        adm_search: "Tìm kiếm...",
        adm_actions: "Thao tác",
        adm_status: "Trạng thái",
        adm_active: "Hoạt động",
        adm_inactive: "Vô hiệu",
        adm_all: "Tất cả",
        adm_no_data: "Không có dữ liệu",
        adm_confirm_delete: "Xác nhận xóa",
        adm_select_complex: "-- Chọn cụm rạp --",
        adm_select_system: "-- Chọn hệ thống --",
        adm_system_label: "Hệ thống rạp",
        adm_complex_label: "Cụm rạp",
        adm_assigned_complex: "Cụm rạp phụ trách",
        adm_not_assigned: "Chưa được phân công cụm rạp",

        // Dashboard
        dash_subtitle: "Tổng quan hệ thống quản lý rạp chiếu phim",
        dash_total_movies: "Tổng số phim",
        dash_now_showing: "Đang chiếu",
        dash_coming_soon: "Sắp chiếu",
        dash_hot_movies: "Phim Hot",
        dash_cinema_systems: "Hệ thống rạp",
        dash_cinema_complexes: "Cụm rạp",
        dash_banners: "Banner",
        dash_recent_movies: "Phim mới cập nhật",
        dash_col_title: "Tên phim",
        dash_col_duration: "Thời lượng",
        dash_col_status: "Trạng thái",
        dash_col_release: "Ngày phát hành",
        dash_status_showing: "Đang chiếu",
        dash_status_coming: "Sắp chiếu",
        dash_status_stopped: "Ngừng chiếu",
        dash_no_movies: "Chưa có phim nào",
        dash_minutes: "phút",

        // Cinemas (Screening rooms)
        cin_title: "Quản lý Phòng chiếu",
        cin_subtitle_admin: "Chọn hệ thống và cụm rạp để quản lý phòng chiếu và sơ đồ ghế.",
        cin_subtitle_staff: "Quản lý phòng chiếu và sơ đồ ghế của cụm rạp bạn phụ trách.",
        cin_room_list: "Danh sách phòng chiếu",
        cin_add_room: "Thêm phòng",
        cin_no_rooms: "Chưa có phòng chiếu nào trong cụm rạp này.",
        cin_room: "Phòng chiếu",
        cin_room_name: "Tên phòng chiếu",
        cin_seats: "Ghế",
        cin_delete_room: "Xóa phòng chiếu",
        cin_delete_room_msg: "Bạn có chắc muốn xóa phòng này? Toàn bộ ghế sẽ bị xóa theo.",

        // Showtimes
        sho_title: "Quản lý Lịch chiếu",
        sho_subtitle_admin: "Chọn hệ thống và cụm rạp để quản lý suất chiếu.",
        sho_subtitle_staff: "Quản lý suất chiếu của cụm rạp bạn phụ trách.",
        sho_list: "Danh sách suất chiếu",
        sho_add: "Thêm suất chiếu",
        sho_none: "Chưa có suất chiếu nào.",
        sho_col_movie: "Phim",
        sho_col_room: "Phòng",
        sho_col_time: "Thời gian",
        sho_col_format: "Định dạng",
        sho_col_price: "Giá vé",

        // Foods
        food_title: "Đồ ăn & Combo",
        food_subtitle_admin: "Quản lý menu đồ ăn và combo theo từng cụm rạp.",
        food_subtitle_staff: "Quản lý menu đồ ăn và combo của cụm rạp bạn phụ trách.",
        food_search: "Tìm tên món...",
        food_add: "Thêm món",
        food_none: "Chưa có món nào trong cụm rạp này.",

        // Staff management
        staff_title: "Quản lý nhân viên",
        staff_subtitle: "Tạo và phân công nhân viên (staff) cho từng cụm rạp",
        staff_add: "Thêm nhân viên",
        staff_total: "Tổng nhân viên",
        staff_active: "Đang hoạt động",
        staff_complex_count: "Cụm rạp có staff",
        staff_search: "Tìm theo email hoặc họ tên...",
        staff_none: "Chưa có nhân viên nào",
        staff_col_staff: "Nhân viên",
        staff_col_contact: "Liên hệ",
        staff_col_complex: "Cụm rạp phụ trách",

        // Movies
        mov_title: "Quản lý Phim",
        mov_subtitle: "Quản lý danh sách phim trong hệ thống",
        mov_search: "Tìm kiếm phim...",
        mov_add: "Thêm phim",
        mov_col_image: "Ảnh",
        mov_col_title: "Tên phim",
        mov_col_duration: "Thời lượng",
        mov_col_category: "Phân loại",

        // Cinema systems
        sys_title: "Quản lý Hệ thống rạp",
        sys_subtitle: "Quản lý các thương hiệu / hệ thống rạp chiếu phim",
        sys_search: "Tìm hệ thống rạp...",
        sys_add: "Thêm hệ thống",
        sys_none: "Chưa có hệ thống rạp nào",
        sys_col_name: "Tên hệ thống",
        sys_col_logo: "Logo",

        // Cinema complexes
        cpx_title: "Quản lý Cụm rạp",
        cpx_subtitle: "Quản lý các cụm rạp thuộc từng hệ thống",
        cpx_search: "Tìm cụm rạp...",
        cpx_add: "Thêm cụm rạp",
        cpx_none: "Chưa có cụm rạp nào",
        cpx_col_name: "Tên cụm rạp",
        cpx_col_address: "Địa chỉ",
        cpx_col_rooms: "Số phòng",

        // Banners
        ban_title: "Quản lý Banner",
        ban_subtitle: "Banner hiển thị ở trang chủ",
        ban_add: "Thêm banner",
        ban_none: "Chưa có banner nào",

        // Vouchers
        vou_title: "Quản lý Mã giảm giá",
        vou_subtitle: "Tạo và quản lý mã khuyến mãi",
        vou_search: "Tìm mã giảm giá...",
        vou_add: "Thêm mã",
        vou_none: "Chưa có mã giảm giá nào",
        vou_staff_scope: "Quản lý mã giảm giá cho cụm rạp:",
        vou_code: "Mã",
        vou_type: "Loại",
        vou_value: "Giá trị",
        vou_max_discount: "Giảm tối đa",
        vou_validity: "Thời hạn",
        vou_used: "Đã dùng",
        vou_status: "Trạng thái",
        vou_actions: "Thao tác",
        vou_loading: "Đang tải...",
        vou_expired: "Hết hạn",
        vou_active: "Đang áp dụng",
        vou_create_title: "Tạo mã giảm giá mới",
        vou_edit_title: "Cập nhật mã giảm giá",
        vou_code_label: "Mã giảm giá *",
        vou_code_placeholder: "VD: SALE50",
        vou_type_label: "Loại giảm giá *",
        vou_type_percent: "Phần trăm (%)",
        vou_type_fixed: "Cố định (VND)",
        vou_value_label: "Giá trị giảm *",
        vou_max_label: "Giảm tối đa (VND)",
        vou_min_label: "Đơn tối thiểu (VND)",
        vou_limit_label: "Giới hạn sử dụng",
        vou_limit_placeholder: "Không giới hạn",
        vou_start_label: "Ngày bắt đầu *",
        vou_end_label: "Ngày kết thúc *",
        vou_complex_label: "Cụm rạp áp dụng",
        vou_complex_default: "Toàn quốc",
        vou_staff_complex_hint: "(mặc định rạp của bạn)",
        vou_broadcast: "Gửi thông báo Broadcast cho toàn hệ thống",
        vou_cancel: "Hủy",
        vou_save: "Cập nhật",
        vou_create: "Tạo mới",
        vou_delete_title: "Xóa mã giảm giá",
        vou_delete_confirm: 'Bạn có chắc chắn muốn xóa mã "{code}"?',
        vou_delete_btn: "Xóa",
        vou_fetch_error: "Không thể tải danh sách mã giảm giá",
        vou_delete_success: "Xóa mã giảm giá thành công",
        vou_update_success: "Cập nhật mã giảm giá thành công",
        vou_create_success: "Tạo mã giảm giá thành công",
        vou_form_required: "Vui lòng điền đầy đủ thông tin bắt buộc",

        // Users
        usr_title: "Quản lý Người dùng",
        usr_subtitle: "Xem danh sách, chi tiết và vô hiệu hóa tài khoản",
        usr_search: "Tìm theo tên, email, SĐT...",
        usr_all_roles: "Tất cả vai trò",
        usr_none: "Chưa có người dùng nào",
        usr_col_name: "Họ tên",
        usr_col_phone: "SĐT",
        usr_col_role: "Vai trò",

        // Notifications
        noti_title: "Quản lý Thông báo",
        noti_subtitle: "Gửi thông báo tới người dùng",
        noti_add: "Tạo thông báo",
        noti_none: "Chưa có thông báo nào",

        // Recommendations
        rec_title: "Recommend System & Email Marketing",
        rec_subtitle: "Quản lý hệ thống gợi ý phim và chiến dịch email",

        // Statistics
        stat_title: "Thống kê",
        stat_subtitle: "Báo cáo và phân tích hệ thống",
        stat_loading: "Đang tải thống kê...",
        stat_load_error: "Không thể tải dữ liệu thống kê",
        stat_total_revenue: "Tổng doanh thu",
        stat_tickets_sold: "Vé đã bán",
        stat_users: "Người dùng",
        stat_total_movies: "Tổng số phim",
        stat_revenue_chart: "Biểu đồ doanh thu",
        stat_days: "ngày",
        stat_no_revenue: "Chưa có dữ liệu doanh thu",
        stat_top_movies: "Top phim doanh thu cao nhất",
        stat_no_data: "Chưa có dữ liệu",
        stat_revenue_by_complex: "Doanh thu theo cụm rạp",

        // Recommendations (detail)
        rec_analysis_title: "Phân tích Recommend",
        rec_analysis_desc: "Ép Worker chạy AI phân tích ngay",
        rec_force_analysis: "Force Run Analysis",
        rec_running: "Đang chạy...",
        rec_email_title: "Gửi Email Marketing",
        rec_email_desc: "Ép Worker gửi email ngay lập tức",
        rec_force_email: "Force Run Email",
        rec_sending: "Đang gửi...",
        rec_campaign_stats: "Thống kê chiến dịch Email",
        rec_emails_sent: "Email đã gửi",
        rec_active_cron: "CronJob đang hoạt động",
        rec_add_cron: "Thêm CronJob",
        rec_no_cron: "Chưa có CronJob nào đang hoạt động",
        rec_create_cron: "Tạo CronJob mới",
        rec_cron_type: "Loại",
        rec_cron_type_analysis: "Phân tích AI Recommend",
        rec_cron_expr: "Biểu thức Cron",
        rec_cron_expr_hint: 'Cấu trúc: [Phút] [Giờ] [Ngày] [Tháng] [Thứ]. VD: "0 8 * * *" = 8h sáng mỗi ngày',
        rec_cron_name: "Tên định danh",
        rec_delete_cron: "Xóa CronJob",
        rec_delete_cron_msg: "Bạn có chắc chắn muốn xóa CronJob này?",
    },
    en: {
        // Navigation / Header
        nav_movies: "Movies",
        nav_cinemas: "Cinemas",
        nav_news: "Promotions",
        search_placeholder: "Search movies, cinemas...",
        login: "Login",
        register: "Register",
        profile: "Profile",
        booked_tickets: "Booked Tickets",
        change_password: "Change Password",
        logout: "Logout",
        theme_light: "Light Theme",
        theme_dark: "Dark Theme",
        notifications: "Notifications",
        no_notifications: "No new notifications",

        // Home / Hero
        explore_now: "Explore Now",
        infinite_journey: "Infinite Journey",
        hero_desc: "A sci-fi cinematic masterpiece taking you to the most distant stars. Discover the mysteries of the universe in a journey full of emotions and stunning visuals.",
        more_info: "More Info",

        // Home / Promotions
        special_promotions: "Special Promotions",
        claim_code: "Claim Code",
        claimed: "Claimed ✓",
        promo_family_title: "Family Sunday",
        promo_family_desc: "Get 20% off family combo when watching movies on Sundays.",
        promo_vip_title: "20% Member Discount",
        promo_vip_desc: "Special offer: 20% discount on ticket prices for VIP members of mievoh.",
        promo_student_title: "Student Special",
        promo_student_desc: "Flat rate of 45K for students on weekdays from Monday to Thursday.",
        promo_night_title: "Late Night Ticket",
        promo_night_desc: "Flat rate of 50K for showtimes after 22:00 daily for night owls.",
        promo_couple_title: "Sweet Couple Combo",
        promo_couple_desc: "Save 10% when purchasing a Couple Combo (2 drinks + 1 large popcorn) at the concession stand.",

        // Home / News
        movie_news: "Movie News",
        see_all: "See All",
        news_art1_title: "Top 5 must-watch movies this month",
        news_art1_desc: "A roundup of the cinematic blockbusters rocking the box office that you can't miss.",
        news_art2_title: "Exclusive interview with the director of \"Infinite Journey\"",
        news_art2_desc: "Discover the creative process behind the sci-fi masterpiece that is currently taking the world by storm.",
        news_art3_title: "Revealing never-before-seen behind-the-scenes secrets",
        news_art3_desc: "Let's take a look at the interesting things happening behind the scenes of major cinematic projects.",
        news_cat_news: "News",
        news_cat_interview: "Interview",
        news_cat_bts: "Behind the scenes",

        // Login / Register
        sign_up_title: "Sign Up",
        sign_up_subtitle: "Join the Mievoh cinema community",
        username: "Username",
        full_name: "Full Name",
        email_address: "Email Address",
        phone_number: "Phone Number",
        password: "Password",
        confirm_password: "Confirm Password",
        signing_up: "Signing up...",
        sign_in_title: "Sign In",
        sign_in_subtitle: "Welcome back to Mievoh Cinema",
        forgot_password: "Forgot password?",
        forgot_password_title: "Forgot Password",
        forgot_password_subtitle: "Enter your email address to recover your account",
        verify_email: "Verify Email",
        verifying: "Verifying...",
        back_to_sign_in: "Back to Sign In",
        reset_password_title: "Reset Password",
        reset_password_subtitle: "Enter your new secure password",
        new_password: "New Password",
        confirm_new_password: "Confirm Password",
        reset_password_btn: "Reset Password",
        resetting: "Resetting...",
        signing_in: "Signing in...",
        or_divider: "or",
        sign_in_google: "Sign in with Google",
        toast_otp_sent: "OTP code has been sent to your email.",
        otp_invalid_length: "OTP code must be 6 digits.",
        otp_modal_title: "OTP Verification",
        otp_modal_subtitle: "We have sent a 6-digit verification code to the email",
        otp_input_placeholder: "Enter OTP code",
        otp_verify_btn: "Verify OTP",
        otp_verifying: "Verifying...",
        otp_resend_btn: "Resend OTP",
        otp_resending: "Resending...",
        otp_cancel_btn: "Cancel",
        welcome_back_overlay: "Welcome Back!",
        welcome_back_desc: "To continue connecting with us, please sign in",
        hello_friend_overlay: "Hello New Friend!",
        hello_friend_desc: "Enter your personal details to start your journey",
        sign_up_now: "SIGN UP NOW",
        already_have_account: "Already have an account?",
        already_have_account_desc: "Sign in now to keep booking blockbuster tickets and get exclusive deals from Mievoh!",
        sign_in_btn: "SIGN IN",
        cancel_btn: "Cancel",

        // Validation & Messages
        email_registered: "This email is already registered",
        validation_required: "This field is required",
        loading: "Loading...",
        no_showtimes: "No showtimes available for this date.",

        // Select Seat
        screen: "Screen",
        seat_status_available: "Available",
        seat_status_selected: "Selected",
        seat_status_booked: "Booked",
        seat_status_holding: "Holding",
        seat_type_regular: "Regular Seat",
        seat_type_vip: "VIP Seat",
        seat_type_sweetbox: "Sweetbox Double Seat",
        booking_summary: "Booking Summary",
        booking_movie: "Movie",
        booking_cinema: "Cinema",
        booking_showtime: "Showtime",
        booking_seats: "Seats",
        booking_combo: "Selected Combo",
        booking_total: "Total",
        booking_continue: "Continue",
        select_seat_title: "Select Seat",

        // Book Ticket / Booking Sidebar / Ticket Page
        select_showtime: "Select Showtime",
        select_date: "Select Date",
        choose_combo: "Choose Combos",
        combo_desc: "Add delicious combo for the best movie experience",
        next_step: "Next Step",
        prev_step: "Go Back",
        payment_method: "Payment Method",
        confirm_payment: "Confirm Payment",
        // Additional Select Seat / Book Ticket / Profile / HotMovies / Cinemas
        stepper_combos: "Combos",
        stepper_payment: "Payment",
        stepper_ticket_info: "Ticket Info",
        booking_hall: "Hall",
        booking_format: "Format",
        no_seats_selected: "No seats selected",
        ticket_price: "Ticket price",
        creating_transaction: "Creating transaction...",
        pay_now: "Pay Now",
        booking_terms_reminder: "Purchased tickets cannot be changed, refunded, or canceled. Please double-check showtime and seat selection details before confirming.",
        toast_account_number_copied: "Account number copied!",
        toast_transfer_content_copied: "Transfer content copied!",
        toast_payment_success: "Payment successful! Your ticket has been issued.",
        toast_screenshot_captured: "Screenshot captured! Please open your banking app to scan.",
        toast_register_success: "Account registered successfully!",
        toast_payment_initiated: "Payment transaction initiated!",
        toast_login_success: "Logged in successfully!",
        toast_login_failed: "Login failed!",
        toast_google_login_success: "Logged in with Google successfully!",
        toast_email_verified_success: "Email verified successfully!",
        toast_password_reset_success: "Password reset successfully!",
        toast_seat_hold_expired: "Seat hold time expired. Please select seats again!",
        toast_max_seats_limit: "You can only select up to 8 seats",
        toast_select_seat_required: "Please select at least one seat before paying",
        toast_fix_info_errors: "Please fix personal info errors",
        toast_username_required: "Username is required!",
        toast_email_required: "Email is required!",
        toast_password_required: "Password is required!",
        cinema_locations_label: "Cinema Locations",

        format_2d_subbed: "2D Subtitles",
        format_2d_dubbed: "2D Dubbed",
        cinema_chains_label: "Cinema Chains",
        cinema_network_title: "Nationwide Cinema Network",
        cinema_network_desc: "Find the nearest cinema branches near you. View detailed addresses, contact info, ticket prices, and showtimes of all top cinema chains in Vietnam.",
        filter_select_location: "Select Location:",
        filter_cinema_chain: "Cinema Chain:",
        filter_quick_search: "Quick Search:",
        filter_all_chains: "All Chains ({count})",
        filter_all_chains_with_count: "All Chains ({count} cinemas)",
        filter_search_placeholder: "Enter cinema name, street...",
        no_cinemas_found: "No cinemas found",
        no_cinemas_found_desc: "Sorry, no cinemas match your current filters. Please try again with other options.",
        clear_filters: "Clear Filters",
        order_confirmation: "Order Confirmation",
        personal_info: "Personal Info",
        total_order_value: "Total Order Value",
        proceed_to_pay: "Proceed to Pay",
        qr_transfer: "QR Code Bank Transfer",
        momo_wallet: "MoMo Wallet",
        zalopay_wallet: "ZaloPay Wallet",
        atm_card: "Local ATM Card",
        qr_transfer_name: "QR Code Bank Transfer",
        qr_transfer_desc: "Scan QR code via banking app to pay",
        momo_name: "MoMo Wallet",
        momo_desc: "Quick payment via MoMo e-wallet",
        zalopay_name: "ZaloPay Wallet",
        zalopay_desc: "Pay via ZaloPay with special promotions",
        atm_name: "Local ATM Card",
        atm_desc: "Payment via local banks",
        back_to_combos: "Go back to combos",
        full_name_placeholder: "Enter your full name",
        phone_number_placeholder: "Enter your phone number",
        email_address_placeholder: "Enter your email address",
        popcorn_drinks_combos: "Popcorn, Drinks & Combos",
        popcorn_combo_discount_desc: "Save up to 20% when purchased together",
        back_to_seats: "Back to seat selection",
        verifying_bank_transfer: "Verifying bank transfer transaction...",
        please_wait_moment: "Please wait a moment",
        transfer_money_to_account: "Transfer money to the following account",
        transfer_time_limit_desc: "You need to transfer within {time} otherwise your seats will be released.",
        bank_label: "Bank",
        account_number_label: "Account Number",
        account_holder_label: "Account Holder",
        transfer_content_label: "Transfer Content",
        copy_btn: "Copy",
        amount_label: "Amount",
        enter_exact_content_desc: "Enter exact content to receive the ticket code.",
        hotline_reminder_desc: "The system automatically issues the ticket code within 30s after your successful transfer. Please contact hotline 024 7308 8890 if you do not receive the ticket code.",
        cancel_transaction: "Cancel Transaction",
        confirm_successful_transfer: "I have successfully transferred",
        screenshot_qr_desc: "Take a screenshot to scan the QR code",
        booking_success_title: "Booking Successful!",
        booking_success_desc: "Thank you for choosing Mievoh. Your showtime awaits you.",
        booking_hall_seats: "Hall & Seats",
        attached_combos: "Attached Combos",
        total_amount_paid: "Total Amount Paid:",
        scan_barcode_desc: "Scan barcode at the cinema to print ticket entry pass",
        back_to_homepage: "Back to Homepage",
        movie_details: "Movie Details",
        cinema_locations: "Cinema Locations",
        no_cinemas_available: "No cinemas available",
        no_cinemas_available_desc: "Please change your location filter or select another showtime date.",
        trending_movies: "Trending Movies",
        recommended_movies: "Recommended for you",
        quick_book: "Quick Book",
        featured_cinemas: "Featured Cinemas",
        see_all_cinemas: "See All",
        view_showtimes: "View Showtimes",
        access_denied: "Access Denied",
        profile_access_denied_desc: "Please log in to view your profile dashboard and booking transactions.",
        session_expired: "Session expired. Please log in again.",
        login_now_btn: "Log In Now",
        click_star_avatar: "Click the star to select and update your avatar",
        avatar_url_label: "Avatar (URL)",
        change_password_title: "Change Password",
        ticket_history_title: "Ticket History",
        avatar_updated_success: "Avatar updated successfully!",
        profile_updated_success: "Profile updated successfully!",
        failed_to_update_profile: "Failed to update profile",
        no_name_registered: "No name registered",
        no_email_registered: "No email registered",
        no_phone_number_registered: "No phone number registered",
        gender: "Gender",
        gender_not_selected: "Gender not selected",
        gender_male: "Male",
        gender_female: "Female",
        select_gender: "Select Gender",
        age: "Age",
        age_not_provided: "Age not provided",
        age_auto_calculated: "Age (Auto-calculated)",
        calculated_from_dob: "Calculated from DOB",
        date_of_birth: "Date of Birth",
        dob_not_set: "Date of birth not set",
        dob_day: "Day",
        dob_month: "Month",
        dob_year: "Year",
        address: "Address",
        address_not_set: "Address not set",
        cccd: "National ID",
        cccd_not_linked: "National ID not linked",
        edit_profile_btn: "Edit Profile",
        saving_btn: "Saving...",
        saved_btn: "Saved!",
        save_changes_btn: "Save Changes",
        current_password: "Current Password",
        current_password_required: "Current password is required",
        current_password_placeholder: "Enter your current password",
        new_password_placeholder: "Enter your new password",
        confirm_new_password_placeholder: "Confirm your new password",
        password_changed_success: "Password changed successfully!",
        password_changed_failed: "Failed to change password",
        updating_btn: "Updating...",
        updated_success_btn: "Updated Successfully!",
        update_password_btn: "Update Password",
        no_tickets_booked: "No tickets booked yet.",
        paid_status: "Paid",
        booked_on: "Booked on",
        view_ticket_code: "View ticket code",
        click_to_scan: "Click to scan",
        ticket_receipt_code: "Ticket Receipt Code",
        scan_at_counter_desc: "Scan barcode at counter to enter hall",
        // Movie System
        genre_action: "Action",
        genre_scifi: "Sci-Fi",
        genre_romance: "Romance",
        genre_music: "Music",
        genre_mystery: "Mystery",
        genre_thriller: "Thriller",
        genre_comedy: "Comedy",
        genre_family: "Family",
        genre_adventure: "Adventure",
        genre_animation: "Animation",
        genre_crime: "Crime",
        genre_horror: "Horror",
        genre_sports: "Sports",
        genre_drama: "Drama",
        genre_documentary: "Documentary",
        genre_nature: "Nature",

        coming_soon: "Coming Soon",
        now_showing: "Now Showing",
        buy_ticket: "Buy Ticket",
        get_notified: "Get Notified",
        subscribed_notifications: "Subscribed to notifications for \"{title}\" when released!",

        release_date: "Release Date",
        director: "Director",
        cast: "Cast",
        age_rating: "Age Rating",
        duration: "Duration",
        language_label: "Language",
        based_on_reviews: "(5.0 / 5 based on reviews)",
        reviews_audience: "Audience Reviews ({count})",
        reviews_star_count: "{count} stars",
        reviews_based_on: "Based on {count} reviews",
        reviews_no_reviews: "No reviews yet. Be the first to review!",
        reviews_write_review: "Write Your Review",
        reviews_your_rating: "Your rating:",
        reviews_your_name: "Your Name *",
        reviews_name_placeholder: "Enter your name to display on your review...",
        reviews_comment_label: "Comment content:",
        reviews_comment_placeholder: "Share your thoughts about this movie...",
        reviews_submit: "Submit Review",
        reviews_enter_name_toast: "Please enter your name!",
        reviews_enter_comment_toast: "Please write a comment!",
        reviews_success_toast: "Thank you for submitting your review!",
        watch_trailer: "Watch Trailer",
        movie_not_found: "Movie Not Found",
        movie_not_found_desc: "Sorry, the requested movie does not exist or is no longer showing.",
        back_to_movie_list: "Back to Movie List",

        movie_list_title: "Movie List",
        movie_list_subtitle: "Explore the ultimate cinematic world with the hottest now showing and upcoming blockbuster movies at Mievoh.",

        all_filter: "All",
        all_locations: "All Locations",
        now_showing_filter: "Now Showing",
        coming_soon_filter: "Coming Soon",
        search_movies_placeholder: "Search movies...",
        sort_by_label: "Sort by:",
        highest_rating: "Highest Rating",
        title_az: "Title (A - Z)",
        title_za: "Title (Z - A)",
        genre_label: "Genre:",

        twod_dubbed: "2D Dubbed",
        twod_subbed: "2D Subbed",
        footer_desc: "Ultimate cinematic experience. Book tickets easily, enjoy fully.",
        footer_rights: "© 2024 mievoh. All rights reserved.",
        footer_explore: "Explore",
        footer_about: "About Us",
        footer_terms: "Terms of Service",
        footer_privacy: "Privacy Policy",
        footer_support: "Support",
        footer_help: "Help Center",
        footer_contact: "Contact Us",
        footer_faq: "FAQ",
        footer_download: "Download App",
        opening_booking_for: "Opening ticket booking for: {title}",
        booking_saved_history_success: "Successfully saved booking {code} to your history!",

        // Admin
        admin_dashboard: "Dashboard",
        admin_movies: "Movie Management",
        admin_cinema_systems: "Cinema Systems",
        admin_cinema_complexes: "Cinema Complexes",
        admin_cinemas: "Screening Rooms",
        admin_showtimes: "Showtimes",
        admin_foods: "Food & Combos",
        admin_banners: "Banners",
        admin_staff: "Staff Management",
        admin_users: "User Management",
        admin_vouchers: "Vouchers",
        admin_notifications: "Notifications",
        admin_recommendations: "Recommend & Email",
        admin_statistics: "Statistics",
        admin_title: "Mievoh Staff",
        admin_access_denied: "Access Denied",
        admin_no_permission: "You do not have permission to access the admin panel.",
        admin_switch_member: "Member",
        admin_switch_admin: "Admin",

        // Admin - Common actions / labels
        adm_loading: "Loading...",
        adm_loading_data: "Loading data...",
        adm_saving: "Saving...",
        adm_save: "Save",
        adm_add: "Add",
        adm_update: "Update",
        adm_cancel: "Cancel",
        adm_delete: "Delete",
        adm_edit: "Edit",
        adm_close: "Close",
        adm_search: "Search...",
        adm_actions: "Actions",
        adm_status: "Status",
        adm_active: "Active",
        adm_inactive: "Inactive",
        adm_all: "All",
        adm_no_data: "No data",
        adm_confirm_delete: "Confirm delete",
        adm_select_complex: "-- Select complex --",
        adm_select_system: "-- Select system --",
        adm_system_label: "Cinema system",
        adm_complex_label: "Cinema complex",
        adm_assigned_complex: "Assigned complex",
        adm_not_assigned: "No complex assigned",

        // Dashboard
        dash_subtitle: "Overview of the cinema management system",
        dash_total_movies: "Total movies",
        dash_now_showing: "Now showing",
        dash_coming_soon: "Coming soon",
        dash_hot_movies: "Hot movies",
        dash_cinema_systems: "Cinema systems",
        dash_cinema_complexes: "Cinema complexes",
        dash_banners: "Banners",
        dash_recent_movies: "Recently updated movies",
        dash_col_title: "Movie title",
        dash_col_duration: "Duration",
        dash_col_status: "Status",
        dash_col_release: "Release date",
        dash_status_showing: "Now showing",
        dash_status_coming: "Coming soon",
        dash_status_stopped: "Stopped",
        dash_no_movies: "No movies yet",
        dash_minutes: "min",

        // Cinemas (Screening rooms)
        cin_title: "Screening Rooms",
        cin_subtitle_admin: "Select a system and complex to manage screening rooms and seat maps.",
        cin_subtitle_staff: "Manage screening rooms and seat maps of your assigned complex.",
        cin_room_list: "Screening room list",
        cin_add_room: "Add room",
        cin_no_rooms: "No screening rooms in this complex yet.",
        cin_room: "Screening room",
        cin_room_name: "Room name",
        cin_seats: "Seats",
        cin_delete_room: "Delete screening room",
        cin_delete_room_msg: "Are you sure you want to delete this room? All seats will be deleted too.",

        // Showtimes
        sho_title: "Showtimes",
        sho_subtitle_admin: "Select a system and complex to manage showtimes.",
        sho_subtitle_staff: "Manage showtimes of your assigned complex.",
        sho_list: "Showtime list",
        sho_add: "Add showtime",
        sho_none: "No showtimes yet.",
        sho_col_movie: "Movie",
        sho_col_room: "Room",
        sho_col_time: "Time",
        sho_col_format: "Format",
        sho_col_price: "Price",

        // Foods
        food_title: "Food & Combos",
        food_subtitle_admin: "Manage food menu and combos per complex.",
        food_subtitle_staff: "Manage food menu and combos of your assigned complex.",
        food_search: "Search item name...",
        food_add: "Add item",
        food_none: "No items in this complex yet.",

        // Staff management
        staff_title: "Staff Management",
        staff_subtitle: "Create and assign staff to each complex",
        staff_add: "Add staff",
        staff_total: "Total staff",
        staff_active: "Active",
        staff_complex_count: "Complexes with staff",
        staff_search: "Search by email or name...",
        staff_none: "No staff yet",
        staff_col_staff: "Staff",
        staff_col_contact: "Contact",
        staff_col_complex: "Assigned complex",

        // Movies
        mov_title: "Movie Management",
        mov_subtitle: "Manage the movie catalog in the system",
        mov_search: "Search movies...",
        mov_add: "Add movie",
        mov_col_image: "Image",
        mov_col_title: "Movie title",
        mov_col_duration: "Duration",
        mov_col_category: "Category",

        // Cinema systems
        sys_title: "Cinema Systems",
        sys_subtitle: "Manage cinema brands / systems",
        sys_search: "Search cinema systems...",
        sys_add: "Add system",
        sys_none: "No cinema systems yet",
        sys_col_name: "System name",
        sys_col_logo: "Logo",

        // Cinema complexes
        cpx_title: "Cinema Complexes",
        cpx_subtitle: "Manage complexes under each system",
        cpx_search: "Search complexes...",
        cpx_add: "Add complex",
        cpx_none: "No complexes yet",
        cpx_col_name: "Complex name",
        cpx_col_address: "Address",
        cpx_col_rooms: "Rooms",

        // Banners
        ban_title: "Banner Management",
        ban_subtitle: "Banners displayed on the homepage",
        ban_add: "Add banner",
        ban_none: "No banners yet",

        // Vouchers
        vou_title: "Voucher Management",
        vou_subtitle: "Create and manage promo codes",
        vou_search: "Search vouchers...",
        vou_add: "Add voucher",
        vou_none: "No vouchers yet",
        vou_staff_scope: "Managing vouchers for complex:",
        vou_code: "Code",
        vou_type: "Type",
        vou_value: "Value",
        vou_max_discount: "Max discount",
        vou_validity: "Validity",
        vou_used: "Used",
        vou_status: "Status",
        vou_actions: "Actions",
        vou_loading: "Loading...",
        vou_expired: "Expired",
        vou_active: "Active",
        vou_create_title: "Create new voucher",
        vou_edit_title: "Update voucher",
        vou_code_label: "Voucher code *",
        vou_code_placeholder: "e.g. SALE50",
        vou_type_label: "Discount type *",
        vou_type_percent: "Percentage (%)",
        vou_type_fixed: "Fixed (VND)",
        vou_value_label: "Discount value *",
        vou_max_label: "Max discount (VND)",
        vou_min_label: "Min purchase (VND)",
        vou_limit_label: "Usage limit",
        vou_limit_placeholder: "Unlimited",
        vou_start_label: "Start date *",
        vou_end_label: "End date *",
        vou_complex_label: "Apply to complex",
        vou_complex_default: "All (nationwide)",
        vou_staff_complex_hint: "(your complex by default)",
        vou_broadcast: "Send broadcast notification to all users",
        vou_cancel: "Cancel",
        vou_save: "Update",
        vou_create: "Create",
        vou_delete_title: "Delete voucher",
        vou_delete_confirm: 'Are you sure you want to delete "{code}"?',
        vou_delete_btn: "Delete",
        vou_fetch_error: "Failed to load vouchers",
        vou_delete_success: "Voucher deleted successfully",
        vou_update_success: "Voucher updated successfully",
        vou_create_success: "Voucher created successfully",
        vou_form_required: "Please fill in all required fields",

        // Users
        usr_title: "User Management",
        usr_subtitle: "View list, details and deactivate accounts",
        usr_search: "Search by name, email, phone...",
        usr_all_roles: "All roles",
        usr_none: "No users yet",
        usr_col_name: "Full name",
        usr_col_phone: "Phone",
        usr_col_role: "Role",

        // Notifications
        noti_title: "Notification Management",
        noti_subtitle: "Send notifications to users",
        noti_add: "Create notification",
        noti_none: "No notifications yet",

        // Recommendations
        rec_title: "Recommend System & Email Marketing",
        rec_subtitle: "Manage movie recommendation system and email campaigns",

        // Statistics
        stat_title: "Statistics",
        stat_subtitle: "System reports and analytics",
        stat_loading: "Loading statistics...",
        stat_load_error: "Unable to load statistics data",
        stat_total_revenue: "Total revenue",
        stat_tickets_sold: "Tickets sold",
        stat_users: "Users",
        stat_total_movies: "Total movies",
        stat_revenue_chart: "Revenue chart",
        stat_days: "days",
        stat_no_revenue: "No revenue data yet",
        stat_top_movies: "Top revenue movies",
        stat_no_data: "No data yet",
        stat_revenue_by_complex: "Revenue by complex",

        // Recommendations (detail)
        rec_analysis_title: "Recommendation Analysis",
        rec_analysis_desc: "Force the Worker to run AI analysis now",
        rec_force_analysis: "Force Run Analysis",
        rec_running: "Running...",
        rec_email_title: "Send Marketing Email",
        rec_email_desc: "Force the Worker to send emails immediately",
        rec_force_email: "Force Run Email",
        rec_sending: "Sending...",
        rec_campaign_stats: "Email Campaign Statistics",
        rec_emails_sent: "Emails sent",
        rec_active_cron: "Active CronJobs",
        rec_add_cron: "Add CronJob",
        rec_no_cron: "No active CronJobs yet",
        rec_create_cron: "Create new CronJob",
        rec_cron_type: "Type",
        rec_cron_type_analysis: "AI Recommendation Analysis",
        rec_cron_expr: "Cron expression",
        rec_cron_expr_hint: 'Format: [Minute] [Hour] [Day] [Month] [Weekday]. E.g. "0 8 * * *" = 8 AM daily',
        rec_cron_name: "Identifier name",
        rec_delete_cron: "Delete CronJob",
        rec_delete_cron_msg: "Are you sure you want to delete this CronJob?",
    }
};

export type Language = "vi" | "en";
export type TranslationKeys = keyof typeof translations.vi;

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: TranslationKeys, replaceObj?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguageState] = useState<Language>(() => {
        const stored = localStorage.getItem("mievoh_language");
        if (stored === "vi" || stored === "en") return stored;
        return "vi"; // Mặc định là Tiếng Việt
    });

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem("mievoh_language", lang);
    };

    // Hàm dịch t hỗ trợ placeholder, ví dụ: t("welcome_user", { name: "John" })
    const t = (key: TranslationKeys, replaceObj?: Record<string, string | number>): string => {
        const langData = translations[language];
        let text = (langData && langData[key]) || key;

        if (replaceObj) {
            Object.entries(replaceObj).forEach(([k, v]) => {
                text = text.replace(new RegExp(`{${k}}`, "g"), String(v));
            });
        }
        return text;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
}
